spring:
  application:
    name: graphql-springboot-sample

server:
  http2:
    enabled: true

graphql:
  servlet:
#    maxQueryDepth: 6
    maxQueryDepth: 32 # 暂改成32，否则voyager不work
    exception-handlers-enabled: false # ture启用spring exception handle
  playground:
    enabled: true
    headers:
      Authorization: Bearer TOKEN_XYZ
    tabs:
      - name: Bank Account Sample Query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json

voyager:
  enabled: true
